-- LinguaAI multilingual vocabulary expansion (V3).
-- Adds five languages and 120 curated entries per supported language.
-- Total catalog after this migration: 7 languages, 900 vocabulary records.

INSERT INTO languages (id, code, name, levels) VALUES
(3, 'ko', 'Korean', 'TOPIK1,TOPIK2,TOPIK3'),
(4, 'es', 'Spanish', 'A1,A2,B1'),
(5, 'fr', 'French', 'A1,A2,B1'),
(6, 'zh', 'Chinese', 'HSK1,HSK2,HSK3'),
(7, 'de', 'German', 'A1,A2,B1');

CREATE INDEX idx_vocab_language_level ON vocabularies (language_id, level, id);
CREATE INDEX idx_vocab_category ON vocabularies (category);

INSERT INTO vocabularies (id, language_id, level, word, reading, pronunciation, meaning, example, example_translation, category, created_at) VALUES
(1001, 1, 'N5', '挨拶', 'aisatsu', NULL, 'Xin chào', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1002, 1, 'N5', 'さようなら', 'sayounara', NULL, 'Tạm biệt', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1003, 1, 'N5', 'お願い', 'onegai', NULL, 'Làm ơn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1004, 1, 'N5', 'ごめん', 'gomen', NULL, 'Xin lỗi', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1005, 1, 'N5', 'はい', 'hai', NULL, 'Có / đúng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1006, 1, 'N5', 'いいえ', 'iie', NULL, 'Không', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1007, 1, 'N5', '名前', 'namae', NULL, 'Tên', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1008, 1, 'N5', '人', 'hito', NULL, 'Người', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1009, 1, 'N5', '子ども', 'kodomo', NULL, 'Trẻ em', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1010, 1, 'N5', '親', 'oya', NULL, 'Cha mẹ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1011, 1, 'N5', '同僚', 'douryou', NULL, 'Đồng nghiệp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1012, 1, 'N5', '客', 'kyaku', NULL, 'Khách hàng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1013, 1, 'N5', '上司', 'joushi', NULL, 'Sếp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1014, 1, 'N5', '招待客', 'shoutaikyaku', NULL, 'Khách', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1015, 1, 'N5', '近所', 'kinjo', NULL, 'Hàng xóm', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1016, 1, 'N5', '住所', 'juusho', NULL, 'Địa chỉ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1017, 1, 'N5', 'メール', 'meeru', NULL, 'Email', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1018, 1, 'N5', 'メッセージ', 'messeeji', NULL, 'Tin nhắn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1019, 1, 'N5', '会議', 'kaigi', NULL, 'Cuộc họp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1020, 1, 'N5', '予定', 'yotei', NULL, 'Lịch hẹn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1021, 1, 'N5', '家', 'ie', NULL, 'Nhà', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1022, 1, 'N5', '部屋', 'heya', NULL, 'Phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1023, 1, 'N5', 'ドア', 'doa', NULL, 'Cửa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1024, 1, 'N5', '窓', 'mado', NULL, 'Cửa sổ', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1025, 1, 'N5', 'テーブル', 'teeburu', NULL, 'Bàn', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1026, 1, 'N5', '椅子', 'isu', NULL, 'Ghế', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1027, 1, 'N5', 'ベッド', 'beddo', NULL, 'Giường', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1028, 1, 'N5', '台所', 'daidokoro', NULL, 'Nhà bếp', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1029, 1, 'N5', '浴室', 'yokushitsu', NULL, 'Phòng tắm', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1030, 1, 'N5', '鍵', 'kagi', NULL, 'Chìa khóa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1031, 1, 'N5', 'コンピューター', 'konpyuutaa', NULL, 'Máy tính', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1032, 1, 'N5', '本', 'hon', NULL, 'Sách', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1033, 1, 'N5', 'かばん', 'kaban', NULL, 'Túi', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1034, 1, 'N5', '服', 'fuku', NULL, 'Quần áo', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1035, 1, 'N5', '靴', 'kutsu', NULL, 'Giày', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1036, 1, 'N5', 'お金', 'okane', NULL, 'Tiền', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1037, 1, 'N5', '値段', 'nedan', NULL, 'Giá', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1038, 1, 'N5', '店', 'mise', NULL, 'Cửa hàng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1039, 1, 'N5', '事務所', 'jimusho', NULL, 'Văn phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1040, 1, 'N5', '切符', 'kippu', NULL, 'Vé', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1041, 1, 'N5', 'パン', 'pan', NULL, 'Bánh mì', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1042, 1, 'N5', 'コーヒー', 'koohii', NULL, 'Cà phê', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1043, 1, 'N5', 'お茶', 'ocha', NULL, 'Trà', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1044, 1, 'N5', '牛乳', 'gyuunyuu', NULL, 'Sữa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1045, 1, 'N5', 'りんご', 'ringo', NULL, 'Táo', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1046, 1, 'N5', '野菜', 'yasai', NULL, 'Rau', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1047, 1, 'N5', '果物', 'kudamono', NULL, 'Trái cây', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1048, 1, 'N5', '朝ご飯', 'asagohan', NULL, 'Bữa sáng', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1049, 1, 'N5', '昼ご飯', 'hirugohan', NULL, 'Bữa trưa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1050, 1, 'N5', '晩ご飯', 'bangohan', NULL, 'Bữa tối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1051, 1, 'N5', '塩', 'shio', NULL, 'Muối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1052, 1, 'N5', '砂糖', 'satou', NULL, 'Đường', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1053, 1, 'N5', 'おいしい', 'oishii', NULL, 'Ngon', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1054, 1, 'N5', 'お腹がすく', 'onaka ga suku', NULL, 'Đói', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1055, 1, 'N5', 'のどが渇く', 'nodo ga kawaku', NULL, 'Khát', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1056, 1, 'N5', 'メニュー', 'menyuu', NULL, 'Thực đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1057, 1, 'N5', '注文', 'chuumon', NULL, 'Món đặt', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1058, 1, 'N5', '会計', 'kaikei', NULL, 'Hóa đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1059, 1, 'N5', '皿', 'sara', NULL, 'Đĩa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1060, 1, 'N5', 'ボトル', 'botoru', NULL, 'Chai', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1061, 1, 'N4', '今日', 'kyou', NULL, 'Hôm nay', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1062, 1, 'N4', '明日', 'ashita', NULL, 'Ngày mai', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1063, 1, 'N4', '昨日', 'kinou', NULL, 'Hôm qua', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1064, 1, 'N4', '朝', 'asa', NULL, 'Buổi sáng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1065, 1, 'N4', '午後', 'gogo', NULL, 'Buổi chiều', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1066, 1, 'N4', '夕方', 'yuugata', NULL, 'Buổi tối', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1067, 1, 'N4', '夜', 'yoru', NULL, 'Ban đêm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1068, 1, 'N4', '週', 'shuu', NULL, 'Tuần', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1069, 1, 'N4', '月', 'tsuki', NULL, 'Tháng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1070, 1, 'N4', '年', 'toshi', NULL, 'Năm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1071, 1, 'N4', 'ホテル', 'hoteru', NULL, 'Khách sạn', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1072, 1, 'N4', '都市', 'toshi', NULL, 'Thành phố', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1073, 1, 'N4', '国', 'kuni', NULL, 'Đất nước', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1074, 1, 'N4', '電車', 'densha', NULL, 'Tàu hỏa', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1075, 1, 'N4', 'バス', 'basu', NULL, 'Xe buýt', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1076, 1, 'N4', '自転車', 'jitensha', NULL, 'Xe đạp', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1077, 1, 'N4', '図書館', 'toshokan', NULL, 'Thư viện', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1078, 1, 'N4', '公園', 'kouen', NULL, 'Công viên', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1079, 1, 'N4', '道', 'michi', NULL, 'Con đường', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1080, 1, 'N4', '地図', 'chizu', NULL, 'Bản đồ', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1081, 1, 'N4', '太陽', 'taiyou', NULL, 'Mặt trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1082, 1, 'N4', '雪', 'yuki', NULL, 'Tuyết', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1083, 1, 'N4', '風', 'kaze', NULL, 'Gió', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1084, 1, 'N4', '山', 'yama', NULL, 'Núi', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1085, 1, 'N4', '川', 'kawa', NULL, 'Sông', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1086, 1, 'N4', '海', 'umi', NULL, 'Biển', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1087, 1, 'N4', '木', 'ki', NULL, 'Cây', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1088, 1, 'N4', '花', 'hana', NULL, 'Hoa', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1089, 1, 'N4', '動物', 'doubutsu', NULL, 'Động vật', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1090, 1, 'N4', '空', 'sora', NULL, 'Bầu trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1091, 1, 'N3', '行く', 'iku', NULL, 'Đi', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1092, 1, 'N3', '来る', 'kuru', NULL, 'Đến', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1093, 1, 'N3', '食べる', 'taberu', NULL, 'Ăn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1094, 1, 'N3', '飲む', 'nomu', NULL, 'Uống', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1095, 1, 'N3', '寝る', 'neru', NULL, 'Ngủ', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1096, 1, 'N3', '起きる', 'okiru', NULL, 'Thức dậy', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1097, 1, 'N3', '勉強する', 'benkyou suru', NULL, 'Học', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1098, 1, 'N3', '働く', 'hataraku', NULL, 'Làm việc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1099, 1, 'N3', '読む', 'yomu', NULL, 'Đọc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1100, 1, 'N3', '書く', 'kaku', NULL, 'Viết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1101, 1, 'N3', '聞く', 'kiku', NULL, 'Lắng nghe', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1102, 1, 'N3', '話す', 'hanasu', NULL, 'Nói', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1103, 1, 'N3', '買う', 'kau', NULL, 'Mua', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1104, 1, 'N3', '売る', 'uru', NULL, 'Bán', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1105, 1, 'N3', '作る', 'tsukuru', NULL, 'Làm / tạo', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1106, 1, 'N3', '使う', 'tsukau', NULL, 'Sử dụng', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1107, 1, 'N3', '必要とする', 'hitsuyou to suru', NULL, 'Cần', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1108, 1, 'N3', '欲しい', 'hoshii', NULL, 'Muốn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1109, 1, 'N3', '知る', 'shiru', NULL, 'Biết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1110, 1, 'N3', '分かる', 'wakaru', NULL, 'Hiểu', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1111, 1, 'N3', '良い', 'ii', NULL, 'Tốt', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1112, 1, 'N3', '悪い', 'warui', NULL, 'Xấu', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1113, 1, 'N3', '大きい', 'ookii', NULL, 'Lớn', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1114, 1, 'N3', '小さい', 'chiisai', NULL, 'Nhỏ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1115, 1, 'N3', '新しい', 'atarashii', NULL, 'Mới', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1116, 1, 'N3', '古い', 'furui', NULL, 'Cũ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1117, 1, 'N3', '易しい', 'yasashii', NULL, 'Dễ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1118, 1, 'N3', '難しい', 'muzukashii', NULL, 'Khó', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1119, 1, 'N3', '可能', 'kanou', NULL, 'Có thể', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1120, 1, 'N3', '便利', 'benri', NULL, 'Hữu ích', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1121, 2, 'A1', 'greeting', NULL, NULL, 'Xin chào', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1122, 2, 'A1', 'goodbye', NULL, NULL, 'Tạm biệt', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1123, 2, 'A1', 'please', NULL, NULL, 'Làm ơn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1124, 2, 'A1', 'sorry', NULL, NULL, 'Xin lỗi', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1125, 2, 'A1', 'yes', NULL, NULL, 'Có / đúng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1126, 2, 'A1', 'no', NULL, NULL, 'Không', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1127, 2, 'A1', 'name', NULL, NULL, 'Tên', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1128, 2, 'A1', 'person', NULL, NULL, 'Người', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1129, 2, 'A1', 'child', NULL, NULL, 'Trẻ em', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1130, 2, 'A1', 'parent', NULL, NULL, 'Cha mẹ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1131, 2, 'A1', 'colleague', NULL, NULL, 'Đồng nghiệp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1132, 2, 'A1', 'customer', NULL, NULL, 'Khách hàng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1133, 2, 'A1', 'boss', NULL, NULL, 'Sếp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1134, 2, 'A1', 'guest', NULL, NULL, 'Khách', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1135, 2, 'A1', 'neighbor', NULL, NULL, 'Hàng xóm', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1136, 2, 'A1', 'address', NULL, NULL, 'Địa chỉ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1137, 2, 'A1', 'email', NULL, NULL, 'Email', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1138, 2, 'A1', 'message', NULL, NULL, 'Tin nhắn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1139, 2, 'A1', 'meeting', NULL, NULL, 'Cuộc họp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1140, 2, 'A1', 'schedule', NULL, NULL, 'Lịch hẹn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1141, 2, 'A1', 'house', NULL, NULL, 'Nhà', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1142, 2, 'A1', 'room', NULL, NULL, 'Phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1143, 2, 'A1', 'door', NULL, NULL, 'Cửa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1144, 2, 'A1', 'window', NULL, NULL, 'Cửa sổ', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1145, 2, 'A1', 'table', NULL, NULL, 'Bàn', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1146, 2, 'A1', 'chair', NULL, NULL, 'Ghế', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1147, 2, 'A1', 'bed', NULL, NULL, 'Giường', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1148, 2, 'A1', 'kitchen', NULL, NULL, 'Nhà bếp', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1149, 2, 'A1', 'bathroom', NULL, NULL, 'Phòng tắm', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1150, 2, 'A1', 'key', NULL, NULL, 'Chìa khóa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1151, 2, 'A1', 'computer', NULL, NULL, 'Máy tính', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1152, 2, 'A1', 'book', NULL, NULL, 'Sách', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1153, 2, 'A1', 'bag', NULL, NULL, 'Túi', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1154, 2, 'A1', 'clothes', NULL, NULL, 'Quần áo', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1155, 2, 'A1', 'shoes', NULL, NULL, 'Giày', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1156, 2, 'A1', 'money', NULL, NULL, 'Tiền', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1157, 2, 'A1', 'price', NULL, NULL, 'Giá', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1158, 2, 'A1', 'shop', NULL, NULL, 'Cửa hàng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1159, 2, 'A1', 'office', NULL, NULL, 'Văn phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1160, 2, 'A1', 'ticket', NULL, NULL, 'Vé', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1161, 2, 'A1', 'bread', NULL, NULL, 'Bánh mì', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1162, 2, 'A1', 'coffee', NULL, NULL, 'Cà phê', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1163, 2, 'A1', 'tea', NULL, NULL, 'Trà', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1164, 2, 'A1', 'milk', NULL, NULL, 'Sữa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1165, 2, 'A1', 'apple', NULL, NULL, 'Táo', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1166, 2, 'A1', 'vegetable', NULL, NULL, 'Rau', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1167, 2, 'A1', 'fruit', NULL, NULL, 'Trái cây', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1168, 2, 'A1', 'breakfast', NULL, NULL, 'Bữa sáng', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1169, 2, 'A1', 'lunch', NULL, NULL, 'Bữa trưa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1170, 2, 'A1', 'dinner', NULL, NULL, 'Bữa tối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1171, 2, 'A1', 'salt', NULL, NULL, 'Muối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1172, 2, 'A1', 'sugar', NULL, NULL, 'Đường', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1173, 2, 'A1', 'delicious', NULL, NULL, 'Ngon', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1174, 2, 'A1', 'hungry', NULL, NULL, 'Đói', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1175, 2, 'A1', 'thirsty', NULL, NULL, 'Khát', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1176, 2, 'A1', 'menu', NULL, NULL, 'Thực đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1177, 2, 'A1', 'order', NULL, NULL, 'Món đặt', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1178, 2, 'A1', 'bill', NULL, NULL, 'Hóa đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1179, 2, 'A1', 'plate', NULL, NULL, 'Đĩa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1180, 2, 'A1', 'bottle', NULL, NULL, 'Chai', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1181, 2, 'A2', 'today', NULL, NULL, 'Hôm nay', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1182, 2, 'A2', 'tomorrow', NULL, NULL, 'Ngày mai', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1183, 2, 'A2', 'yesterday', NULL, NULL, 'Hôm qua', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1184, 2, 'A2', 'morning', NULL, NULL, 'Buổi sáng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1185, 2, 'A2', 'afternoon', NULL, NULL, 'Buổi chiều', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1186, 2, 'A2', 'evening', NULL, NULL, 'Buổi tối', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1187, 2, 'A2', 'night', NULL, NULL, 'Ban đêm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1188, 2, 'A2', 'week', NULL, NULL, 'Tuần', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1189, 2, 'A2', 'month', NULL, NULL, 'Tháng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1190, 2, 'A2', 'year', NULL, NULL, 'Năm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1191, 2, 'A2', 'hotel', NULL, NULL, 'Khách sạn', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1192, 2, 'A2', 'city', NULL, NULL, 'Thành phố', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1193, 2, 'A2', 'country', NULL, NULL, 'Đất nước', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1194, 2, 'A2', 'train', NULL, NULL, 'Tàu hỏa', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1195, 2, 'A2', 'bus', NULL, NULL, 'Xe buýt', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1196, 2, 'A2', 'bicycle', NULL, NULL, 'Xe đạp', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1197, 2, 'A2', 'library', NULL, NULL, 'Thư viện', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1198, 2, 'A2', 'park', NULL, NULL, 'Công viên', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1199, 2, 'A2', 'road', NULL, NULL, 'Con đường', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1200, 2, 'A2', 'map', NULL, NULL, 'Bản đồ', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1201, 2, 'A2', 'sun', NULL, NULL, 'Mặt trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1202, 2, 'A2', 'snow', NULL, NULL, 'Tuyết', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1203, 2, 'A2', 'wind', NULL, NULL, 'Gió', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1204, 2, 'A2', 'mountain', NULL, NULL, 'Núi', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1205, 2, 'A2', 'river', NULL, NULL, 'Sông', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1206, 2, 'A2', 'sea', NULL, NULL, 'Biển', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1207, 2, 'A2', 'tree', NULL, NULL, 'Cây', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1208, 2, 'A2', 'flower', NULL, NULL, 'Hoa', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1209, 2, 'A2', 'animal', NULL, NULL, 'Động vật', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1210, 2, 'A2', 'sky', NULL, NULL, 'Bầu trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1211, 2, 'B1', 'go', NULL, NULL, 'Đi', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1212, 2, 'B1', 'come', NULL, NULL, 'Đến', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1213, 2, 'B1', 'eat', NULL, NULL, 'Ăn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1214, 2, 'B1', 'drink', NULL, NULL, 'Uống', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1215, 2, 'B1', 'sleep', NULL, NULL, 'Ngủ', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1216, 2, 'B1', 'wake', NULL, NULL, 'Thức dậy', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1217, 2, 'B1', 'study', NULL, NULL, 'Học', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1218, 2, 'B1', 'work', NULL, NULL, 'Làm việc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1219, 2, 'B1', 'read', NULL, NULL, 'Đọc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1220, 2, 'B1', 'write', NULL, NULL, 'Viết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1221, 2, 'B1', 'listen', NULL, NULL, 'Lắng nghe', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1222, 2, 'B1', 'speak', NULL, NULL, 'Nói', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1223, 2, 'B1', 'buy', NULL, NULL, 'Mua', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1224, 2, 'B1', 'sell', NULL, NULL, 'Bán', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1225, 2, 'B1', 'make', NULL, NULL, 'Làm / tạo', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1226, 2, 'B1', 'use', NULL, NULL, 'Sử dụng', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1227, 2, 'B1', 'need', NULL, NULL, 'Cần', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1228, 2, 'B1', 'want', NULL, NULL, 'Muốn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1229, 2, 'B1', 'know', NULL, NULL, 'Biết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1230, 2, 'B1', 'understand', NULL, NULL, 'Hiểu', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1231, 2, 'B1', 'good', NULL, NULL, 'Tốt', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1232, 2, 'B1', 'bad', NULL, NULL, 'Xấu', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1233, 2, 'B1', 'big', NULL, NULL, 'Lớn', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1234, 2, 'B1', 'small', NULL, NULL, 'Nhỏ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1235, 2, 'B1', 'new', NULL, NULL, 'Mới', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1236, 2, 'B1', 'old', NULL, NULL, 'Cũ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1237, 2, 'B1', 'easy', NULL, NULL, 'Dễ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1238, 2, 'B1', 'difficult', NULL, NULL, 'Khó', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1239, 2, 'B1', 'possible', NULL, NULL, 'Có thể', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1240, 2, 'B1', 'useful', NULL, NULL, 'Hữu ích', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1241, 3, 'TOPIK1', '인사', 'insa', NULL, 'Xin chào', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1242, 3, 'TOPIK1', '안녕히 가세요', 'annyeonghi gaseyo', NULL, 'Tạm biệt', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1243, 3, 'TOPIK1', '부탁', 'butak', NULL, 'Làm ơn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1244, 3, 'TOPIK1', '미안합니다', 'mianhamnida', NULL, 'Xin lỗi', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1245, 3, 'TOPIK1', '네', 'ne', NULL, 'Có / đúng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1246, 3, 'TOPIK1', '아니요', 'aniyo', NULL, 'Không', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1247, 3, 'TOPIK1', '이름', 'ireum', NULL, 'Tên', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1248, 3, 'TOPIK1', '사람', 'saram', NULL, 'Người', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1249, 3, 'TOPIK1', '아이', 'ai', NULL, 'Trẻ em', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1250, 3, 'TOPIK1', '부모님', 'bumonim', NULL, 'Cha mẹ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1251, 3, 'TOPIK1', '동료', 'dongnyo', NULL, 'Đồng nghiệp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1252, 3, 'TOPIK1', '고객', 'gogaek', NULL, 'Khách hàng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1253, 3, 'TOPIK1', '상사', 'sangsa', NULL, 'Sếp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1254, 3, 'TOPIK1', '손님', 'sonnim', NULL, 'Khách', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1255, 3, 'TOPIK1', '이웃', 'iut', NULL, 'Hàng xóm', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1256, 3, 'TOPIK1', '주소', 'juso', NULL, 'Địa chỉ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1257, 3, 'TOPIK1', '이메일', 'imeil', NULL, 'Email', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1258, 3, 'TOPIK1', '메시지', 'mesiji', NULL, 'Tin nhắn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1259, 3, 'TOPIK1', '회의', 'hoeui', NULL, 'Cuộc họp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1260, 3, 'TOPIK1', '약속', 'yaksok', NULL, 'Lịch hẹn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1261, 3, 'TOPIK1', '집', 'jip', NULL, 'Nhà', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1262, 3, 'TOPIK1', '방', 'bang', NULL, 'Phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1263, 3, 'TOPIK1', '문', 'mun', NULL, 'Cửa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1264, 3, 'TOPIK1', '창문', 'changmun', NULL, 'Cửa sổ', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1265, 3, 'TOPIK1', '탁자', 'takja', NULL, 'Bàn', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1266, 3, 'TOPIK1', '의자', 'uija', NULL, 'Ghế', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1267, 3, 'TOPIK1', '침대', 'chimdae', NULL, 'Giường', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1268, 3, 'TOPIK1', '부엌', 'bueok', NULL, 'Nhà bếp', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1269, 3, 'TOPIK1', '화장실', 'hwajangsil', NULL, 'Phòng tắm', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1270, 3, 'TOPIK1', '열쇠', 'yeolsoe', NULL, 'Chìa khóa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1271, 3, 'TOPIK1', '컴퓨터', 'keompyuteo', NULL, 'Máy tính', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1272, 3, 'TOPIK1', '책', 'chaek', NULL, 'Sách', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1273, 3, 'TOPIK1', '가방', 'gabang', NULL, 'Túi', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1274, 3, 'TOPIK1', '옷', 'ot', NULL, 'Quần áo', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1275, 3, 'TOPIK1', '신발', 'sinbal', NULL, 'Giày', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1276, 3, 'TOPIK1', '돈', 'don', NULL, 'Tiền', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1277, 3, 'TOPIK1', '가격', 'gagyeok', NULL, 'Giá', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1278, 3, 'TOPIK1', '가게', 'gage', NULL, 'Cửa hàng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1279, 3, 'TOPIK1', '사무실', 'samusil', NULL, 'Văn phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1280, 3, 'TOPIK1', '표', 'pyo', NULL, 'Vé', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1281, 3, 'TOPIK1', '빵', 'ppang', NULL, 'Bánh mì', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1282, 3, 'TOPIK1', '커피', 'keopi', NULL, 'Cà phê', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1283, 3, 'TOPIK1', '차', 'cha', NULL, 'Trà', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1284, 3, 'TOPIK1', '우유', 'uyu', NULL, 'Sữa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1285, 3, 'TOPIK1', '사과', 'sagwa', NULL, 'Táo', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1286, 3, 'TOPIK1', '채소', 'chaeso', NULL, 'Rau', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1287, 3, 'TOPIK1', '과일', 'gwail', NULL, 'Trái cây', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1288, 3, 'TOPIK1', '아침식사', 'achimsiksa', NULL, 'Bữa sáng', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1289, 3, 'TOPIK1', '점심식사', 'jeomsimsiksa', NULL, 'Bữa trưa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1290, 3, 'TOPIK1', '저녁식사', 'jeonyeoksiksa', NULL, 'Bữa tối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1291, 3, 'TOPIK1', '소금', 'sogeum', NULL, 'Muối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1292, 3, 'TOPIK1', '설탕', 'seoltang', NULL, 'Đường', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1293, 3, 'TOPIK1', '맛있다', 'masitda', NULL, 'Ngon', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1294, 3, 'TOPIK1', '배고프다', 'baegopeuda', NULL, 'Đói', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1295, 3, 'TOPIK1', '목마르다', 'mokmareuda', NULL, 'Khát', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1296, 3, 'TOPIK1', '메뉴', 'menyu', NULL, 'Thực đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1297, 3, 'TOPIK1', '주문', 'jumun', NULL, 'Món đặt', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1298, 3, 'TOPIK1', '계산', 'gyesan', NULL, 'Hóa đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1299, 3, 'TOPIK1', '접시', 'jeopsi', NULL, 'Đĩa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1300, 3, 'TOPIK1', '병', 'byeong', NULL, 'Chai', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1301, 3, 'TOPIK2', '오늘', 'oneul', NULL, 'Hôm nay', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1302, 3, 'TOPIK2', '내일', 'naeil', NULL, 'Ngày mai', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1303, 3, 'TOPIK2', '어제', 'eoje', NULL, 'Hôm qua', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1304, 3, 'TOPIK2', '아침', 'achim', NULL, 'Buổi sáng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1305, 3, 'TOPIK2', '오후', 'ohu', NULL, 'Buổi chiều', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1306, 3, 'TOPIK2', '저녁', 'jeonyeok', NULL, 'Buổi tối', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1307, 3, 'TOPIK2', '밤', 'bam', NULL, 'Ban đêm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1308, 3, 'TOPIK2', '주', 'ju', NULL, 'Tuần', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1309, 3, 'TOPIK2', '달', 'dal', NULL, 'Tháng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1310, 3, 'TOPIK2', '해', 'hae', NULL, 'Năm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1311, 3, 'TOPIK2', '호텔', 'hotel', NULL, 'Khách sạn', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1312, 3, 'TOPIK2', '도시', 'dosi', NULL, 'Thành phố', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1313, 3, 'TOPIK2', '나라', 'nara', NULL, 'Đất nước', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1314, 3, 'TOPIK2', '기차', 'gicha', NULL, 'Tàu hỏa', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1315, 3, 'TOPIK2', '버스', 'beoseu', NULL, 'Xe buýt', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1316, 3, 'TOPIK2', '자전거', 'jajeongeo', NULL, 'Xe đạp', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1317, 3, 'TOPIK2', '도서관', 'doseogwan', NULL, 'Thư viện', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1318, 3, 'TOPIK2', '공원', 'gongwon', NULL, 'Công viên', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1319, 3, 'TOPIK2', '길', 'gil', NULL, 'Con đường', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1320, 3, 'TOPIK2', '지도', 'jido', NULL, 'Bản đồ', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1321, 3, 'TOPIK2', '태양', 'taeyang', NULL, 'Mặt trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1322, 3, 'TOPIK2', '눈', 'nun', NULL, 'Tuyết', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1323, 3, 'TOPIK2', '바람', 'baram', NULL, 'Gió', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1324, 3, 'TOPIK2', '산', 'san', NULL, 'Núi', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1325, 3, 'TOPIK2', '강', 'gang', NULL, 'Sông', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1326, 3, 'TOPIK2', '바다', 'bada', NULL, 'Biển', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1327, 3, 'TOPIK2', '나무', 'namu', NULL, 'Cây', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1328, 3, 'TOPIK2', '꽃', 'kkot', NULL, 'Hoa', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1329, 3, 'TOPIK2', '동물', 'dongmul', NULL, 'Động vật', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1330, 3, 'TOPIK2', '하늘', 'haneul', NULL, 'Bầu trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1331, 3, 'TOPIK3', '가다', 'gada', NULL, 'Đi', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1332, 3, 'TOPIK3', '오다', 'oda', NULL, 'Đến', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1333, 3, 'TOPIK3', '먹다', 'meokda', NULL, 'Ăn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1334, 3, 'TOPIK3', '마시다', 'masida', NULL, 'Uống', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1335, 3, 'TOPIK3', '자다', 'jada', NULL, 'Ngủ', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1336, 3, 'TOPIK3', '일어나다', 'ireonada', NULL, 'Thức dậy', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1337, 3, 'TOPIK3', '공부하다', 'gongbuhada', NULL, 'Học', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1338, 3, 'TOPIK3', '일하다', 'ilhada', NULL, 'Làm việc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1339, 3, 'TOPIK3', '읽다', 'ilkda', NULL, 'Đọc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1340, 3, 'TOPIK3', '쓰다', 'sseuda', NULL, 'Viết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1341, 3, 'TOPIK3', '듣다', 'deutda', NULL, 'Lắng nghe', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1342, 3, 'TOPIK3', '말하다', 'malhada', NULL, 'Nói', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1343, 3, 'TOPIK3', '사다', 'sada', NULL, 'Mua', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1344, 3, 'TOPIK3', '팔다', 'palda', NULL, 'Bán', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1345, 3, 'TOPIK3', '만들다', 'mandeulda', NULL, 'Làm / tạo', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1346, 3, 'TOPIK3', '사용하다', 'sayonghada', NULL, 'Sử dụng', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1347, 3, 'TOPIK3', '필요하다', 'piryohada', NULL, 'Cần', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1348, 3, 'TOPIK3', '원하다', 'wonhada', NULL, 'Muốn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1349, 3, 'TOPIK3', '알다', 'alda', NULL, 'Biết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1350, 3, 'TOPIK3', '이해하다', 'ihaehada', NULL, 'Hiểu', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1351, 3, 'TOPIK3', '좋다', 'jota', NULL, 'Tốt', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1352, 3, 'TOPIK3', '나쁘다', 'nappeuda', NULL, 'Xấu', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1353, 3, 'TOPIK3', '크다', 'keuda', NULL, 'Lớn', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1354, 3, 'TOPIK3', '작다', 'jakda', NULL, 'Nhỏ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1355, 3, 'TOPIK3', '새롭다', 'saeropda', NULL, 'Mới', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1356, 3, 'TOPIK3', '오래되다', 'oraedoeda', NULL, 'Cũ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1357, 3, 'TOPIK3', '쉽다', 'swipda', NULL, 'Dễ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1358, 3, 'TOPIK3', '어렵다', 'eoryeopda', NULL, 'Khó', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1359, 3, 'TOPIK3', '가능하다', 'ganeunghada', NULL, 'Có thể', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1360, 3, 'TOPIK3', '유용하다', 'yuyonghada', NULL, 'Hữu ích', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1361, 4, 'A1', 'hola', NULL, NULL, 'Xin chào', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1362, 4, 'A1', 'adiós', NULL, NULL, 'Tạm biệt', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1363, 4, 'A1', 'por favor', NULL, NULL, 'Làm ơn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1364, 4, 'A1', 'perdón', NULL, NULL, 'Xin lỗi', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1365, 4, 'A1', 'sí', NULL, NULL, 'Có / đúng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1366, 4, 'A1', 'no', NULL, NULL, 'Không', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1367, 4, 'A1', 'nombre', NULL, NULL, 'Tên', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1368, 4, 'A1', 'persona', NULL, NULL, 'Người', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1369, 4, 'A1', 'niño', NULL, NULL, 'Trẻ em', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1370, 4, 'A1', 'padre', NULL, NULL, 'Cha mẹ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1371, 4, 'A1', 'colega', NULL, NULL, 'Đồng nghiệp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1372, 4, 'A1', 'cliente', NULL, NULL, 'Khách hàng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1373, 4, 'A1', 'jefe', NULL, NULL, 'Sếp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1374, 4, 'A1', 'invitado', NULL, NULL, 'Khách', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1375, 4, 'A1', 'vecino', NULL, NULL, 'Hàng xóm', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1376, 4, 'A1', 'dirección', NULL, NULL, 'Địa chỉ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1377, 4, 'A1', 'correo', NULL, NULL, 'Email', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1378, 4, 'A1', 'mensaje', NULL, NULL, 'Tin nhắn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1379, 4, 'A1', 'reunión', NULL, NULL, 'Cuộc họp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1380, 4, 'A1', 'cita', NULL, NULL, 'Lịch hẹn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1381, 4, 'A1', 'casa', NULL, NULL, 'Nhà', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1382, 4, 'A1', 'habitación', NULL, NULL, 'Phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1383, 4, 'A1', 'puerta', NULL, NULL, 'Cửa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1384, 4, 'A1', 'ventana', NULL, NULL, 'Cửa sổ', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1385, 4, 'A1', 'mesa', NULL, NULL, 'Bàn', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1386, 4, 'A1', 'silla', NULL, NULL, 'Ghế', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1387, 4, 'A1', 'cama', NULL, NULL, 'Giường', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1388, 4, 'A1', 'cocina', NULL, NULL, 'Nhà bếp', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1389, 4, 'A1', 'baño', NULL, NULL, 'Phòng tắm', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1390, 4, 'A1', 'llave', NULL, NULL, 'Chìa khóa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1391, 4, 'A1', 'computadora', NULL, NULL, 'Máy tính', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1392, 4, 'A1', 'libro', NULL, NULL, 'Sách', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1393, 4, 'A1', 'bolso', NULL, NULL, 'Túi', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1394, 4, 'A1', 'ropa', NULL, NULL, 'Quần áo', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1395, 4, 'A1', 'zapatos', NULL, NULL, 'Giày', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1396, 4, 'A1', 'dinero', NULL, NULL, 'Tiền', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1397, 4, 'A1', 'precio', NULL, NULL, 'Giá', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1398, 4, 'A1', 'tienda', NULL, NULL, 'Cửa hàng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1399, 4, 'A1', 'oficina', NULL, NULL, 'Văn phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1400, 4, 'A1', 'boleto', NULL, NULL, 'Vé', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1401, 4, 'A1', 'pan', NULL, NULL, 'Bánh mì', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1402, 4, 'A1', 'café', NULL, NULL, 'Cà phê', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1403, 4, 'A1', 'té', NULL, NULL, 'Trà', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1404, 4, 'A1', 'leche', NULL, NULL, 'Sữa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1405, 4, 'A1', 'manzana', NULL, NULL, 'Táo', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1406, 4, 'A1', 'verdura', NULL, NULL, 'Rau', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1407, 4, 'A1', 'fruta', NULL, NULL, 'Trái cây', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1408, 4, 'A1', 'desayuno', NULL, NULL, 'Bữa sáng', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1409, 4, 'A1', 'almuerzo', NULL, NULL, 'Bữa trưa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1410, 4, 'A1', 'cena', NULL, NULL, 'Bữa tối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1411, 4, 'A1', 'sal', NULL, NULL, 'Muối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1412, 4, 'A1', 'azúcar', NULL, NULL, 'Đường', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1413, 4, 'A1', 'delicioso', NULL, NULL, 'Ngon', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1414, 4, 'A1', 'hambriento', NULL, NULL, 'Đói', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1415, 4, 'A1', 'sediento', NULL, NULL, 'Khát', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1416, 4, 'A1', 'menú', NULL, NULL, 'Thực đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1417, 4, 'A1', 'pedido', NULL, NULL, 'Món đặt', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1418, 4, 'A1', 'cuenta', NULL, NULL, 'Hóa đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1419, 4, 'A1', 'plato', NULL, NULL, 'Đĩa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1420, 4, 'A1', 'botella', NULL, NULL, 'Chai', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1421, 4, 'A2', 'hoy', NULL, NULL, 'Hôm nay', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1422, 4, 'A2', 'mañana', NULL, NULL, 'Ngày mai', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1423, 4, 'A2', 'ayer', NULL, NULL, 'Hôm qua', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1424, 4, 'A2', 'la mañana', NULL, NULL, 'Buổi sáng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1425, 4, 'A2', 'la tarde', NULL, NULL, 'Buổi chiều', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1426, 4, 'A2', 'la noche', NULL, NULL, 'Buổi tối', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1427, 4, 'A2', 'de noche', NULL, NULL, 'Ban đêm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1428, 4, 'A2', 'semana', NULL, NULL, 'Tuần', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1429, 4, 'A2', 'mes', NULL, NULL, 'Tháng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1430, 4, 'A2', 'año', NULL, NULL, 'Năm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1431, 4, 'A2', 'hotel', NULL, NULL, 'Khách sạn', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1432, 4, 'A2', 'ciudad', NULL, NULL, 'Thành phố', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1433, 4, 'A2', 'país', NULL, NULL, 'Đất nước', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1434, 4, 'A2', 'tren', NULL, NULL, 'Tàu hỏa', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1435, 4, 'A2', 'autobús', NULL, NULL, 'Xe buýt', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1436, 4, 'A2', 'bicicleta', NULL, NULL, 'Xe đạp', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1437, 4, 'A2', 'biblioteca', NULL, NULL, 'Thư viện', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1438, 4, 'A2', 'parque', NULL, NULL, 'Công viên', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1439, 4, 'A2', 'carretera', NULL, NULL, 'Con đường', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1440, 4, 'A2', 'mapa', NULL, NULL, 'Bản đồ', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1441, 4, 'A2', 'sol', NULL, NULL, 'Mặt trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1442, 4, 'A2', 'nieve', NULL, NULL, 'Tuyết', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1443, 4, 'A2', 'viento', NULL, NULL, 'Gió', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1444, 4, 'A2', 'montaña', NULL, NULL, 'Núi', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1445, 4, 'A2', 'río', NULL, NULL, 'Sông', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1446, 4, 'A2', 'mar', NULL, NULL, 'Biển', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1447, 4, 'A2', 'árbol', NULL, NULL, 'Cây', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1448, 4, 'A2', 'flor', NULL, NULL, 'Hoa', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1449, 4, 'A2', 'animal', NULL, NULL, 'Động vật', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1450, 4, 'A2', 'cielo', NULL, NULL, 'Bầu trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1451, 4, 'B1', 'ir', NULL, NULL, 'Đi', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1452, 4, 'B1', 'venir', NULL, NULL, 'Đến', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1453, 4, 'B1', 'comer', NULL, NULL, 'Ăn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1454, 4, 'B1', 'beber', NULL, NULL, 'Uống', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1455, 4, 'B1', 'dormir', NULL, NULL, 'Ngủ', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1456, 4, 'B1', 'despertarse', NULL, NULL, 'Thức dậy', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1457, 4, 'B1', 'estudiar', NULL, NULL, 'Học', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1458, 4, 'B1', 'trabajar', NULL, NULL, 'Làm việc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1459, 4, 'B1', 'leer', NULL, NULL, 'Đọc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1460, 4, 'B1', 'escribir', NULL, NULL, 'Viết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1461, 4, 'B1', 'escuchar', NULL, NULL, 'Lắng nghe', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1462, 4, 'B1', 'hablar', NULL, NULL, 'Nói', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1463, 4, 'B1', 'comprar', NULL, NULL, 'Mua', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1464, 4, 'B1', 'vender', NULL, NULL, 'Bán', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1465, 4, 'B1', 'hacer', NULL, NULL, 'Làm / tạo', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1466, 4, 'B1', 'usar', NULL, NULL, 'Sử dụng', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1467, 4, 'B1', 'necesitar', NULL, NULL, 'Cần', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1468, 4, 'B1', 'querer', NULL, NULL, 'Muốn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1469, 4, 'B1', 'saber', NULL, NULL, 'Biết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1470, 4, 'B1', 'entender', NULL, NULL, 'Hiểu', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1471, 4, 'B1', 'bueno', NULL, NULL, 'Tốt', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1472, 4, 'B1', 'malo', NULL, NULL, 'Xấu', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1473, 4, 'B1', 'grande', NULL, NULL, 'Lớn', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1474, 4, 'B1', 'pequeño', NULL, NULL, 'Nhỏ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1475, 4, 'B1', 'nuevo', NULL, NULL, 'Mới', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1476, 4, 'B1', 'antiguo', NULL, NULL, 'Cũ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1477, 4, 'B1', 'fácil', NULL, NULL, 'Dễ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1478, 4, 'B1', 'difícil', NULL, NULL, 'Khó', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1479, 4, 'B1', 'posible', NULL, NULL, 'Có thể', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1480, 4, 'B1', 'útil', NULL, NULL, 'Hữu ích', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1481, 5, 'A1', 'bonjour', NULL, NULL, 'Xin chào', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1482, 5, 'A1', 'au revoir', NULL, NULL, 'Tạm biệt', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1483, 5, 'A1', 's''il vous plaît', NULL, NULL, 'Làm ơn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1484, 5, 'A1', 'désolé', NULL, NULL, 'Xin lỗi', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1485, 5, 'A1', 'oui', NULL, NULL, 'Có / đúng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1486, 5, 'A1', 'non', NULL, NULL, 'Không', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1487, 5, 'A1', 'nom', NULL, NULL, 'Tên', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1488, 5, 'A1', 'personne', NULL, NULL, 'Người', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1489, 5, 'A1', 'enfant', NULL, NULL, 'Trẻ em', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1490, 5, 'A1', 'parent', NULL, NULL, 'Cha mẹ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1491, 5, 'A1', 'collègue', NULL, NULL, 'Đồng nghiệp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1492, 5, 'A1', 'client', NULL, NULL, 'Khách hàng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1493, 5, 'A1', 'patron', NULL, NULL, 'Sếp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1494, 5, 'A1', 'invité', NULL, NULL, 'Khách', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1495, 5, 'A1', 'voisin', NULL, NULL, 'Hàng xóm', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1496, 5, 'A1', 'adresse', NULL, NULL, 'Địa chỉ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1497, 5, 'A1', 'courriel', NULL, NULL, 'Email', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1498, 5, 'A1', 'message', NULL, NULL, 'Tin nhắn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1499, 5, 'A1', 'réunion', NULL, NULL, 'Cuộc họp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1500, 5, 'A1', 'rendez-vous', NULL, NULL, 'Lịch hẹn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1501, 5, 'A1', 'maison', NULL, NULL, 'Nhà', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1502, 5, 'A1', 'chambre', NULL, NULL, 'Phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1503, 5, 'A1', 'porte', NULL, NULL, 'Cửa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1504, 5, 'A1', 'fenêtre', NULL, NULL, 'Cửa sổ', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1505, 5, 'A1', 'table', NULL, NULL, 'Bàn', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1506, 5, 'A1', 'chaise', NULL, NULL, 'Ghế', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1507, 5, 'A1', 'lit', NULL, NULL, 'Giường', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1508, 5, 'A1', 'cuisine', NULL, NULL, 'Nhà bếp', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1509, 5, 'A1', 'salle de bains', NULL, NULL, 'Phòng tắm', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1510, 5, 'A1', 'clé', NULL, NULL, 'Chìa khóa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1511, 5, 'A1', 'ordinateur', NULL, NULL, 'Máy tính', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1512, 5, 'A1', 'livre', NULL, NULL, 'Sách', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1513, 5, 'A1', 'sac', NULL, NULL, 'Túi', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1514, 5, 'A1', 'vêtements', NULL, NULL, 'Quần áo', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1515, 5, 'A1', 'chaussures', NULL, NULL, 'Giày', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1516, 5, 'A1', 'argent', NULL, NULL, 'Tiền', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1517, 5, 'A1', 'prix', NULL, NULL, 'Giá', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1518, 5, 'A1', 'magasin', NULL, NULL, 'Cửa hàng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1519, 5, 'A1', 'bureau', NULL, NULL, 'Văn phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1520, 5, 'A1', 'billet', NULL, NULL, 'Vé', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1521, 5, 'A1', 'pain', NULL, NULL, 'Bánh mì', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1522, 5, 'A1', 'café', NULL, NULL, 'Cà phê', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1523, 5, 'A1', 'thé', NULL, NULL, 'Trà', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1524, 5, 'A1', 'lait', NULL, NULL, 'Sữa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1525, 5, 'A1', 'pomme', NULL, NULL, 'Táo', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1526, 5, 'A1', 'légume', NULL, NULL, 'Rau', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1527, 5, 'A1', 'fruit', NULL, NULL, 'Trái cây', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1528, 5, 'A1', 'petit-déjeuner', NULL, NULL, 'Bữa sáng', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1529, 5, 'A1', 'déjeuner', NULL, NULL, 'Bữa trưa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1530, 5, 'A1', 'dîner', NULL, NULL, 'Bữa tối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1531, 5, 'A1', 'sel', NULL, NULL, 'Muối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1532, 5, 'A1', 'sucre', NULL, NULL, 'Đường', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1533, 5, 'A1', 'délicieux', NULL, NULL, 'Ngon', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1534, 5, 'A1', 'faim', NULL, NULL, 'Đói', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1535, 5, 'A1', 'soif', NULL, NULL, 'Khát', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1536, 5, 'A1', 'menu', NULL, NULL, 'Thực đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1537, 5, 'A1', 'commande', NULL, NULL, 'Món đặt', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1538, 5, 'A1', 'addition', NULL, NULL, 'Hóa đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1539, 5, 'A1', 'assiette', NULL, NULL, 'Đĩa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1540, 5, 'A1', 'bouteille', NULL, NULL, 'Chai', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1541, 5, 'A2', 'aujourd''hui', NULL, NULL, 'Hôm nay', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1542, 5, 'A2', 'demain', NULL, NULL, 'Ngày mai', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1543, 5, 'A2', 'hier', NULL, NULL, 'Hôm qua', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1544, 5, 'A2', 'matin', NULL, NULL, 'Buổi sáng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1545, 5, 'A2', 'après-midi', NULL, NULL, 'Buổi chiều', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1546, 5, 'A2', 'soirée', NULL, NULL, 'Buổi tối', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1547, 5, 'A2', 'nuit', NULL, NULL, 'Ban đêm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1548, 5, 'A2', 'semaine', NULL, NULL, 'Tuần', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1549, 5, 'A2', 'mois', NULL, NULL, 'Tháng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1550, 5, 'A2', 'année', NULL, NULL, 'Năm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1551, 5, 'A2', 'hôtel', NULL, NULL, 'Khách sạn', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1552, 5, 'A2', 'ville', NULL, NULL, 'Thành phố', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1553, 5, 'A2', 'pays', NULL, NULL, 'Đất nước', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1554, 5, 'A2', 'train', NULL, NULL, 'Tàu hỏa', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1555, 5, 'A2', 'bus', NULL, NULL, 'Xe buýt', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1556, 5, 'A2', 'vélo', NULL, NULL, 'Xe đạp', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1557, 5, 'A2', 'bibliothèque', NULL, NULL, 'Thư viện', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1558, 5, 'A2', 'parc', NULL, NULL, 'Công viên', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1559, 5, 'A2', 'route', NULL, NULL, 'Con đường', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1560, 5, 'A2', 'carte', NULL, NULL, 'Bản đồ', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1561, 5, 'A2', 'soleil', NULL, NULL, 'Mặt trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1562, 5, 'A2', 'neige', NULL, NULL, 'Tuyết', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1563, 5, 'A2', 'vent', NULL, NULL, 'Gió', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1564, 5, 'A2', 'montagne', NULL, NULL, 'Núi', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1565, 5, 'A2', 'rivière', NULL, NULL, 'Sông', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1566, 5, 'A2', 'mer', NULL, NULL, 'Biển', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1567, 5, 'A2', 'arbre', NULL, NULL, 'Cây', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1568, 5, 'A2', 'fleur', NULL, NULL, 'Hoa', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1569, 5, 'A2', 'animal', NULL, NULL, 'Động vật', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1570, 5, 'A2', 'ciel', NULL, NULL, 'Bầu trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1571, 5, 'B1', 'aller', NULL, NULL, 'Đi', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1572, 5, 'B1', 'venir', NULL, NULL, 'Đến', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1573, 5, 'B1', 'manger', NULL, NULL, 'Ăn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1574, 5, 'B1', 'boire', NULL, NULL, 'Uống', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1575, 5, 'B1', 'dormir', NULL, NULL, 'Ngủ', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1576, 5, 'B1', 'se réveiller', NULL, NULL, 'Thức dậy', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1577, 5, 'B1', 'étudier', NULL, NULL, 'Học', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1578, 5, 'B1', 'travailler', NULL, NULL, 'Làm việc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1579, 5, 'B1', 'lire', NULL, NULL, 'Đọc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1580, 5, 'B1', 'écrire', NULL, NULL, 'Viết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1581, 5, 'B1', 'écouter', NULL, NULL, 'Lắng nghe', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1582, 5, 'B1', 'parler', NULL, NULL, 'Nói', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1583, 5, 'B1', 'acheter', NULL, NULL, 'Mua', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1584, 5, 'B1', 'vendre', NULL, NULL, 'Bán', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1585, 5, 'B1', 'faire', NULL, NULL, 'Làm / tạo', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1586, 5, 'B1', 'utiliser', NULL, NULL, 'Sử dụng', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1587, 5, 'B1', 'avoir besoin', NULL, NULL, 'Cần', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1588, 5, 'B1', 'vouloir', NULL, NULL, 'Muốn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1589, 5, 'B1', 'savoir', NULL, NULL, 'Biết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1590, 5, 'B1', 'comprendre', NULL, NULL, 'Hiểu', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1591, 5, 'B1', 'bon', NULL, NULL, 'Tốt', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1592, 5, 'B1', 'mauvais', NULL, NULL, 'Xấu', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1593, 5, 'B1', 'grand', NULL, NULL, 'Lớn', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1594, 5, 'B1', 'petit', NULL, NULL, 'Nhỏ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1595, 5, 'B1', 'nouveau', NULL, NULL, 'Mới', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1596, 5, 'B1', 'ancien', NULL, NULL, 'Cũ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1597, 5, 'B1', 'facile', NULL, NULL, 'Dễ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1598, 5, 'B1', 'difficile', NULL, NULL, 'Khó', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1599, 5, 'B1', 'possible', NULL, NULL, 'Có thể', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1600, 5, 'B1', 'utile', NULL, NULL, 'Hữu ích', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1601, 6, 'HSK1', '你好', 'nǐ hǎo', NULL, 'Xin chào', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1602, 6, 'HSK1', '再见', 'zài jiàn', NULL, 'Tạm biệt', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1603, 6, 'HSK1', '请', 'qǐng', NULL, 'Làm ơn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1604, 6, 'HSK1', '对不起', 'duì bu qǐ', NULL, 'Xin lỗi', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1605, 6, 'HSK1', '是', 'shì', NULL, 'Có / đúng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1606, 6, 'HSK1', '不', 'bù', NULL, 'Không', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1607, 6, 'HSK1', '名字', 'míng zi', NULL, 'Tên', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1608, 6, 'HSK1', '人', 'rén', NULL, 'Người', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1609, 6, 'HSK1', '孩子', 'hái zi', NULL, 'Trẻ em', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1610, 6, 'HSK1', '父母', 'fù mǔ', NULL, 'Cha mẹ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1611, 6, 'HSK1', '同事', 'tóng shì', NULL, 'Đồng nghiệp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1612, 6, 'HSK1', '顾客', 'gù kè', NULL, 'Khách hàng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1613, 6, 'HSK1', '老板', 'lǎo bǎn', NULL, 'Sếp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1614, 6, 'HSK1', '客人', 'kè rén', NULL, 'Khách', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1615, 6, 'HSK1', '邻居', 'lín jū', NULL, 'Hàng xóm', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1616, 6, 'HSK1', '地址', 'dì zhǐ', NULL, 'Địa chỉ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1617, 6, 'HSK1', '电子邮件', 'diàn zǐ yóu jiàn', NULL, 'Email', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1618, 6, 'HSK1', '信息', 'xìn xī', NULL, 'Tin nhắn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1619, 6, 'HSK1', '会议', 'huì yì', NULL, 'Cuộc họp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1620, 6, 'HSK1', '约会', 'yuē huì', NULL, 'Lịch hẹn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1621, 6, 'HSK1', '房子', 'fáng zi', NULL, 'Nhà', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1622, 6, 'HSK1', '房间', 'fáng jiān', NULL, 'Phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1623, 6, 'HSK1', '门', 'mén', NULL, 'Cửa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1624, 6, 'HSK1', '窗户', 'chuāng hu', NULL, 'Cửa sổ', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1625, 6, 'HSK1', '桌子', 'zhuō zi', NULL, 'Bàn', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1626, 6, 'HSK1', '椅子', 'yǐ zi', NULL, 'Ghế', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1627, 6, 'HSK1', '床', 'chuáng', NULL, 'Giường', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1628, 6, 'HSK1', '厨房', 'chú fáng', NULL, 'Nhà bếp', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1629, 6, 'HSK1', '浴室', 'yù shì', NULL, 'Phòng tắm', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1630, 6, 'HSK1', '钥匙', 'yào shi', NULL, 'Chìa khóa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1631, 6, 'HSK1', '电脑', 'diàn nǎo', NULL, 'Máy tính', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1632, 6, 'HSK1', '书', 'shū', NULL, 'Sách', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1633, 6, 'HSK1', '包', 'bāo', NULL, 'Túi', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1634, 6, 'HSK1', '衣服', 'yī fu', NULL, 'Quần áo', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1635, 6, 'HSK1', '鞋', 'xié', NULL, 'Giày', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1636, 6, 'HSK1', '钱', 'qián', NULL, 'Tiền', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1637, 6, 'HSK1', '价格', 'jià gé', NULL, 'Giá', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1638, 6, 'HSK1', '商店', 'shāng diàn', NULL, 'Cửa hàng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1639, 6, 'HSK1', '办公室', 'bàn gōng shì', NULL, 'Văn phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1640, 6, 'HSK1', '票', 'piào', NULL, 'Vé', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1641, 6, 'HSK1', '面包', 'miàn bāo', NULL, 'Bánh mì', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1642, 6, 'HSK1', '咖啡', 'kā fēi', NULL, 'Cà phê', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1643, 6, 'HSK1', '茶', 'chá', NULL, 'Trà', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1644, 6, 'HSK1', '牛奶', 'niú nǎi', NULL, 'Sữa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1645, 6, 'HSK1', '苹果', 'píng guǒ', NULL, 'Táo', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1646, 6, 'HSK1', '蔬菜', 'shū cài', NULL, 'Rau', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1647, 6, 'HSK1', '水果', 'shuǐ guǒ', NULL, 'Trái cây', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1648, 6, 'HSK1', '早饭', 'zǎo fàn', NULL, 'Bữa sáng', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1649, 6, 'HSK1', '午饭', 'wǔ fàn', NULL, 'Bữa trưa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1650, 6, 'HSK1', '晚饭', 'wǎn fàn', NULL, 'Bữa tối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1651, 6, 'HSK1', '盐', 'yán', NULL, 'Muối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1652, 6, 'HSK1', '糖', 'táng', NULL, 'Đường', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1653, 6, 'HSK1', '好吃', 'hǎo chī', NULL, 'Ngon', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1654, 6, 'HSK1', '饿', 'è', NULL, 'Đói', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1655, 6, 'HSK1', '渴', 'kě', NULL, 'Khát', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1656, 6, 'HSK1', '菜单', 'cài dān', NULL, 'Thực đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1657, 6, 'HSK1', '订单', 'dìng dān', NULL, 'Món đặt', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1658, 6, 'HSK1', '账单', 'zhàng dān', NULL, 'Hóa đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1659, 6, 'HSK1', '盘子', 'pán zi', NULL, 'Đĩa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1660, 6, 'HSK1', '瓶子', 'píng zi', NULL, 'Chai', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1661, 6, 'HSK2', '今天', 'jīn tiān', NULL, 'Hôm nay', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1662, 6, 'HSK2', '明天', 'míng tiān', NULL, 'Ngày mai', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1663, 6, 'HSK2', '昨天', 'zuó tiān', NULL, 'Hôm qua', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1664, 6, 'HSK2', '早上', 'zǎo shang', NULL, 'Buổi sáng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1665, 6, 'HSK2', '下午', 'xià wǔ', NULL, 'Buổi chiều', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1666, 6, 'HSK2', '傍晚', 'bàng wǎn', NULL, 'Buổi tối', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1667, 6, 'HSK2', '晚上', 'wǎn shang', NULL, 'Ban đêm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1668, 6, 'HSK2', '星期', 'xīng qī', NULL, 'Tuần', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1669, 6, 'HSK2', '月', 'yuè', NULL, 'Tháng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1670, 6, 'HSK2', '年', 'nián', NULL, 'Năm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1671, 6, 'HSK2', '酒店', 'jiǔ diàn', NULL, 'Khách sạn', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1672, 6, 'HSK2', '城市', 'chéng shì', NULL, 'Thành phố', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1673, 6, 'HSK2', '国家', 'guó jiā', NULL, 'Đất nước', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1674, 6, 'HSK2', '火车', 'huǒ chē', NULL, 'Tàu hỏa', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1675, 6, 'HSK2', '公共汽车', 'gōng gòng qì chē', NULL, 'Xe buýt', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1676, 6, 'HSK2', '自行车', 'zì xíng chē', NULL, 'Xe đạp', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1677, 6, 'HSK2', '图书馆', 'tú shū guǎn', NULL, 'Thư viện', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1678, 6, 'HSK2', '公园', 'gōng yuán', NULL, 'Công viên', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1679, 6, 'HSK2', '道路', 'dào lù', NULL, 'Con đường', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1680, 6, 'HSK2', '地图', 'dì tú', NULL, 'Bản đồ', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1681, 6, 'HSK2', '太阳', 'tài yáng', NULL, 'Mặt trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1682, 6, 'HSK2', '雪', 'xuě', NULL, 'Tuyết', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1683, 6, 'HSK2', '风', 'fēng', NULL, 'Gió', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1684, 6, 'HSK2', '山', 'shān', NULL, 'Núi', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1685, 6, 'HSK2', '河', 'hé', NULL, 'Sông', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1686, 6, 'HSK2', '海', 'hǎi', NULL, 'Biển', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1687, 6, 'HSK2', '树', 'shù', NULL, 'Cây', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1688, 6, 'HSK2', '花', 'huā', NULL, 'Hoa', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1689, 6, 'HSK2', '动物', 'dòng wù', NULL, 'Động vật', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1690, 6, 'HSK2', '天空', 'tiān kōng', NULL, 'Bầu trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1691, 6, 'HSK3', '去', 'qù', NULL, 'Đi', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1692, 6, 'HSK3', '来', 'lái', NULL, 'Đến', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1693, 6, 'HSK3', '吃', 'chī', NULL, 'Ăn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1694, 6, 'HSK3', '喝', 'hē', NULL, 'Uống', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1695, 6, 'HSK3', '睡觉', 'shuì jiào', NULL, 'Ngủ', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1696, 6, 'HSK3', '起床', 'qǐ chuáng', NULL, 'Thức dậy', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1697, 6, 'HSK3', '学习', 'xué xí', NULL, 'Học', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1698, 6, 'HSK3', '工作', 'gōng zuò', NULL, 'Làm việc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1699, 6, 'HSK3', '读', 'dú', NULL, 'Đọc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1700, 6, 'HSK3', '写', 'xiě', NULL, 'Viết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1701, 6, 'HSK3', '听', 'tīng', NULL, 'Lắng nghe', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1702, 6, 'HSK3', '说', 'shuō', NULL, 'Nói', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1703, 6, 'HSK3', '买', 'mǎi', NULL, 'Mua', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1704, 6, 'HSK3', '卖', 'mài', NULL, 'Bán', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1705, 6, 'HSK3', '做', 'zuò', NULL, 'Làm / tạo', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1706, 6, 'HSK3', '使用', 'shǐ yòng', NULL, 'Sử dụng', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1707, 6, 'HSK3', '需要', 'xū yào', NULL, 'Cần', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1708, 6, 'HSK3', '想要', 'xiǎng yào', NULL, 'Muốn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1709, 6, 'HSK3', '知道', 'zhī dào', NULL, 'Biết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1710, 6, 'HSK3', '理解', 'lǐ jiě', NULL, 'Hiểu', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1711, 6, 'HSK3', '好', 'hǎo', NULL, 'Tốt', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1712, 6, 'HSK3', '坏', 'huài', NULL, 'Xấu', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1713, 6, 'HSK3', '大', 'dà', NULL, 'Lớn', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1714, 6, 'HSK3', '小', 'xiǎo', NULL, 'Nhỏ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1715, 6, 'HSK3', '新', 'xīn', NULL, 'Mới', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1716, 6, 'HSK3', '旧', 'jiù', NULL, 'Cũ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1717, 6, 'HSK3', '容易', 'róng yì', NULL, 'Dễ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1718, 6, 'HSK3', '困难', 'kùn nán', NULL, 'Khó', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1719, 6, 'HSK3', '可能', 'kě néng', NULL, 'Có thể', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1720, 6, 'HSK3', '有用', 'yǒu yòng', NULL, 'Hữu ích', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1721, 7, 'A1', 'Hallo', NULL, NULL, 'Xin chào', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1722, 7, 'A1', 'Auf Wiedersehen', NULL, NULL, 'Tạm biệt', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1723, 7, 'A1', 'bitte', NULL, NULL, 'Làm ơn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1724, 7, 'A1', 'Entschuldigung', NULL, NULL, 'Xin lỗi', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1725, 7, 'A1', 'ja', NULL, NULL, 'Có / đúng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1726, 7, 'A1', 'nein', NULL, NULL, 'Không', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1727, 7, 'A1', 'Name', NULL, NULL, 'Tên', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1728, 7, 'A1', 'Person', NULL, NULL, 'Người', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1729, 7, 'A1', 'Kind', NULL, NULL, 'Trẻ em', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1730, 7, 'A1', 'Eltern', NULL, NULL, 'Cha mẹ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1731, 7, 'A1', 'Kollege', NULL, NULL, 'Đồng nghiệp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1732, 7, 'A1', 'Kunde', NULL, NULL, 'Khách hàng', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1733, 7, 'A1', 'Chef', NULL, NULL, 'Sếp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1734, 7, 'A1', 'Gast', NULL, NULL, 'Khách', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1735, 7, 'A1', 'Nachbar', NULL, NULL, 'Hàng xóm', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1736, 7, 'A1', 'Adresse', NULL, NULL, 'Địa chỉ', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1737, 7, 'A1', 'E-Mail', NULL, NULL, 'Email', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1738, 7, 'A1', 'Nachricht', NULL, NULL, 'Tin nhắn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1739, 7, 'A1', 'Besprechung', NULL, NULL, 'Cuộc họp', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1740, 7, 'A1', 'Termin', NULL, NULL, 'Lịch hẹn', NULL, NULL, 'Communication', CURRENT_TIMESTAMP),
(1741, 7, 'A1', 'Haus', NULL, NULL, 'Nhà', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1742, 7, 'A1', 'Zimmer', NULL, NULL, 'Phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1743, 7, 'A1', 'Tür', NULL, NULL, 'Cửa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1744, 7, 'A1', 'Fenster', NULL, NULL, 'Cửa sổ', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1745, 7, 'A1', 'Tisch', NULL, NULL, 'Bàn', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1746, 7, 'A1', 'Stuhl', NULL, NULL, 'Ghế', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1747, 7, 'A1', 'Bett', NULL, NULL, 'Giường', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1748, 7, 'A1', 'Küche', NULL, NULL, 'Nhà bếp', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1749, 7, 'A1', 'Badezimmer', NULL, NULL, 'Phòng tắm', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1750, 7, 'A1', 'Schlüssel', NULL, NULL, 'Chìa khóa', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1751, 7, 'A1', 'Computer', NULL, NULL, 'Máy tính', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1752, 7, 'A1', 'Buch', NULL, NULL, 'Sách', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1753, 7, 'A1', 'Tasche', NULL, NULL, 'Túi', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1754, 7, 'A1', 'Kleidung', NULL, NULL, 'Quần áo', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1755, 7, 'A1', 'Schuhe', NULL, NULL, 'Giày', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1756, 7, 'A1', 'Geld', NULL, NULL, 'Tiền', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1757, 7, 'A1', 'Preis', NULL, NULL, 'Giá', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1758, 7, 'A1', 'Geschäft', NULL, NULL, 'Cửa hàng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1759, 7, 'A1', 'Büro', NULL, NULL, 'Văn phòng', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1760, 7, 'A1', 'Ticket', NULL, NULL, 'Vé', NULL, NULL, 'Daily', CURRENT_TIMESTAMP),
(1761, 7, 'A1', 'Brot', NULL, NULL, 'Bánh mì', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1762, 7, 'A1', 'Kaffee', NULL, NULL, 'Cà phê', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1763, 7, 'A1', 'Tee', NULL, NULL, 'Trà', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1764, 7, 'A1', 'Milch', NULL, NULL, 'Sữa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1765, 7, 'A1', 'Apfel', NULL, NULL, 'Táo', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1766, 7, 'A1', 'Gemüse', NULL, NULL, 'Rau', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1767, 7, 'A1', 'Obst', NULL, NULL, 'Trái cây', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1768, 7, 'A1', 'Frühstück', NULL, NULL, 'Bữa sáng', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1769, 7, 'A1', 'Mittagessen', NULL, NULL, 'Bữa trưa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1770, 7, 'A1', 'Abendessen', NULL, NULL, 'Bữa tối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1771, 7, 'A1', 'Salz', NULL, NULL, 'Muối', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1772, 7, 'A1', 'Zucker', NULL, NULL, 'Đường', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1773, 7, 'A1', 'lecker', NULL, NULL, 'Ngon', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1774, 7, 'A1', 'hungrig', NULL, NULL, 'Đói', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1775, 7, 'A1', 'durstig', NULL, NULL, 'Khát', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1776, 7, 'A1', 'Speisekarte', NULL, NULL, 'Thực đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1777, 7, 'A1', 'Bestellung', NULL, NULL, 'Món đặt', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1778, 7, 'A1', 'Rechnung', NULL, NULL, 'Hóa đơn', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1779, 7, 'A1', 'Teller', NULL, NULL, 'Đĩa', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1780, 7, 'A1', 'Flasche', NULL, NULL, 'Chai', NULL, NULL, 'Food', CURRENT_TIMESTAMP),
(1781, 7, 'A2', 'heute', NULL, NULL, 'Hôm nay', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1782, 7, 'A2', 'morgen', NULL, NULL, 'Ngày mai', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1783, 7, 'A2', 'gestern', NULL, NULL, 'Hôm qua', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1784, 7, 'A2', 'Vormittag', NULL, NULL, 'Buổi sáng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1785, 7, 'A2', 'Nachmittag', NULL, NULL, 'Buổi chiều', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1786, 7, 'A2', 'Abend', NULL, NULL, 'Buổi tối', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1787, 7, 'A2', 'Nacht', NULL, NULL, 'Ban đêm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1788, 7, 'A2', 'Woche', NULL, NULL, 'Tuần', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1789, 7, 'A2', 'Monat', NULL, NULL, 'Tháng', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1790, 7, 'A2', 'Jahr', NULL, NULL, 'Năm', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1791, 7, 'A2', 'Hotel', NULL, NULL, 'Khách sạn', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1792, 7, 'A2', 'Stadt', NULL, NULL, 'Thành phố', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1793, 7, 'A2', 'Land', NULL, NULL, 'Đất nước', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1794, 7, 'A2', 'Zug', NULL, NULL, 'Tàu hỏa', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1795, 7, 'A2', 'Bus', NULL, NULL, 'Xe buýt', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1796, 7, 'A2', 'Fahrrad', NULL, NULL, 'Xe đạp', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1797, 7, 'A2', 'Bibliothek', NULL, NULL, 'Thư viện', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1798, 7, 'A2', 'Park', NULL, NULL, 'Công viên', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1799, 7, 'A2', 'Straße', NULL, NULL, 'Con đường', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1800, 7, 'A2', 'Karte', NULL, NULL, 'Bản đồ', NULL, NULL, 'Travel', CURRENT_TIMESTAMP),
(1801, 7, 'A2', 'Sonne', NULL, NULL, 'Mặt trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1802, 7, 'A2', 'Schnee', NULL, NULL, 'Tuyết', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1803, 7, 'A2', 'Wind', NULL, NULL, 'Gió', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1804, 7, 'A2', 'Berg', NULL, NULL, 'Núi', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1805, 7, 'A2', 'Fluss', NULL, NULL, 'Sông', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1806, 7, 'A2', 'Meer', NULL, NULL, 'Biển', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1807, 7, 'A2', 'Baum', NULL, NULL, 'Cây', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1808, 7, 'A2', 'Blume', NULL, NULL, 'Hoa', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1809, 7, 'A2', 'Tier', NULL, NULL, 'Động vật', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1810, 7, 'A2', 'Himmel', NULL, NULL, 'Bầu trời', NULL, NULL, 'Nature', CURRENT_TIMESTAMP),
(1811, 7, 'B1', 'gehen', NULL, NULL, 'Đi', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1812, 7, 'B1', 'kommen', NULL, NULL, 'Đến', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1813, 7, 'B1', 'essen', NULL, NULL, 'Ăn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1814, 7, 'B1', 'trinken', NULL, NULL, 'Uống', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1815, 7, 'B1', 'schlafen', NULL, NULL, 'Ngủ', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1816, 7, 'B1', 'aufwachen', NULL, NULL, 'Thức dậy', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1817, 7, 'B1', 'lernen', NULL, NULL, 'Học', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1818, 7, 'B1', 'arbeiten', NULL, NULL, 'Làm việc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1819, 7, 'B1', 'lesen', NULL, NULL, 'Đọc', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1820, 7, 'B1', 'schreiben', NULL, NULL, 'Viết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1821, 7, 'B1', 'zuhören', NULL, NULL, 'Lắng nghe', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1822, 7, 'B1', 'sprechen', NULL, NULL, 'Nói', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1823, 7, 'B1', 'kaufen', NULL, NULL, 'Mua', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1824, 7, 'B1', 'verkaufen', NULL, NULL, 'Bán', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1825, 7, 'B1', 'machen', NULL, NULL, 'Làm / tạo', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1826, 7, 'B1', 'benutzen', NULL, NULL, 'Sử dụng', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1827, 7, 'B1', 'brauchen', NULL, NULL, 'Cần', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1828, 7, 'B1', 'wollen', NULL, NULL, 'Muốn', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1829, 7, 'B1', 'wissen', NULL, NULL, 'Biết', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1830, 7, 'B1', 'verstehen', NULL, NULL, 'Hiểu', NULL, NULL, 'Verb', CURRENT_TIMESTAMP),
(1831, 7, 'B1', 'gut', NULL, NULL, 'Tốt', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1832, 7, 'B1', 'schlecht', NULL, NULL, 'Xấu', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1833, 7, 'B1', 'groß', NULL, NULL, 'Lớn', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1834, 7, 'B1', 'klein', NULL, NULL, 'Nhỏ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1835, 7, 'B1', 'neu', NULL, NULL, 'Mới', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1836, 7, 'B1', 'alt', NULL, NULL, 'Cũ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1837, 7, 'B1', 'einfach', NULL, NULL, 'Dễ', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1838, 7, 'B1', 'schwierig', NULL, NULL, 'Khó', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1839, 7, 'B1', 'möglich', NULL, NULL, 'Có thể', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP),
(1840, 7, 'B1', 'nützlich', NULL, NULL, 'Hữu ích', NULL, NULL, 'Adjective', CURRENT_TIMESTAMP);
